### ISSUE TITLE
Kvaser CAN Interface - Error opening reader: -2 - A bad parameter was provided to the CAN interface during initalization.

### ISSUE THREAD

**Issue by karry3775** [astuff/kvaser_interface#12]
Followed the steps as provided in the repository.
Gives the above error when running
rosrun kvaser_interface kvaser_can_bridge

**Comment by JWhitleyAStuff** [comment]
@karry3775 This error occurrs when the Kvaser API can not find the hardware ID (serial number) and circuit ID (channel) that you provided. When running the node with rosrun, you must provide these parameters on the command line - they are defaulted to generic numbers. This is why it is easier to use the provided launch file. Here is an example:

`roslaunch kvaser_interface kvaser_can_bridge.launch can_hardware_id:=123456 can_circuit_id:=0`

Replace 123456 with the serial number of your Kvaser device (removing any proceeding 0s) and replace 0 with the 0-based index of the channel you want to use on the Kvaser device.

**Comment by Jasmineyangyangyang** [comment]
what is the serial number of your Kvaser device? how can I can the can_hardware_id in ubuntu20

**Comment by icolwell-as** [comment]
@Jasmineyangyangyang assuming you have kvaser canlib installed, run the following:
```
/usr/src/linuxcan/canlib/examples/listChannels
```

You can install canlib like this:
``` 
sudo apt-add-repository ppa:astuff/kvaser-linux
sudo apt update
sudo apt install kvaser-canlib-dev kvaser-drivers-dkms
```
