### ISSUE TITLE
how could I set the can_bit_rate?

### ISSUE THREAD

**Issue by melodynk** [astuff/kvaser_interface#26]
Hi,I could connect the radar device using these ros package .I wonder that which number I should set with the can_bit_rate .Now I use the default number 500kbps.Should I change this number when it is neccessry?How will it influence the data ouput when I change the can_bit_rate
Thanks so much!

**Comment by JWhitleyAStuff** [comment]
The bit rate is specific to the device that you're connecting to. 500kbps is typical for radars but, for example, J1939 devices (like semi trucks) use 250kbps.
