### ISSUE TITLE
Why does it print error infomation when I use canmonitor tools

### ISSUE THREAD

**Issue by melodynk** [astuff/kvaser_interface#27]
Hi .I could successfully connect the radar system with this ros package.And It could print the can message correctly.However when I use the cannonitor tools with no ROS dependencies(./canmonitor) .It will print error infomation like this below .I wonder why it prints such error.Thaks so much!
![Screenshot from 2019-03-27 16-29-10](https://user-images.githubusercontent.com/37090372/55060961-9cb23600-50ad-11e9-885c-f9a0d70b78f4.png)

**Comment by JWhitleyAStuff** [comment]
The canmonitor tool that is provided with linuxcan defaults to connecting at 1Mbps. If you are attempting to connect to a radar (especially one provided by AutonomouStuff), you will need to change this to 500kbps and recompile the examples. Edit the `canmonitor.c` file in that folder and, somewhere around line 172, you should see a reference to `canBITRATE_1M`. Change this to `canBITRATE_500K` and save the file. Then, inside that folder, type `sudo make` and run `canmonitor` again. You should no longer see the error frames.

As a side note, if you build this repository from source you will now also get a `canmonitor` tool which is, in my opinion, a bit easier to use than the one provided by canlib. The `kvaser_interface` `canmonitor` tool does not rely on ROS either but can be easily launched by running `rosrun kvaser_interface canmonitor` after you build this repository from source (will be released soon).
