### ISSUE TITLE
After 4.0.0 release, extended CAN IDs fail to be transmitted

### ISSUE THREAD

**Issue by JWhitleyAStuff** [astuff/kvaser_interface#30]
The support team found that, post the 4.0.0 release (including the current 4.0.2 release), extended CAN IDs fail to transmit. This will be addressed ASAP and a new release generated after testing.

**Comment by zoakesAStuff** [comment]
A little more detail: 

Bug present at d9ddef2 ("4.0.2") but not present at be2623a ( 3.0.0 (untagged)). After reverting to be2623a issue was no longer present 

To reproduce:
Using a single-channel kvaser leaf light v2 unit set at 250kbaud:

Operation: rostopic pub to /can_rx with an ID greater than 0xffff and is_extended set to true.
Expect: kvaser unit sends message
Observe: no message sent, CAN light on kvaser unit unlit

Operation: rostopic pub to /can_rx with an ID smaller than 0xffff and is_extended set to false.
Expect kvaser unit sends message
Observe: kvaser unit sends message
