### ISSUE TITLE
Question about "CAN send error: -7 - A write operation failed on the CAN interface"

### ISSUE THREAD

**Issue by TIANGANGLIN** [astuff/kvaser_interface#54]
Hello,
I used the  Kvaser Leaf Light v2 and a delphi_esr radar. When I use "roslaunch delphi_esr delphi_esr.launch" commend, it returns "Kvaser CAN Interface - CAN send error: -7 - A write operation failed on the CAN interface", and I receive nothing in rostopic echo /can_tx. I want to know if my implementation is correct or not. Can u send me a tutorial about this? 
Waiting for your reply.

**Comment by icolwell-as** [comment]
Hi, this may help:
https://autonomoustuff.atlassian.net/wiki/spaces/RW/pages/17472305/Populate+CAN+Hardware+and+Circuit+IDs

Definitely check if `listChannels` works and double-check if the delphi driver is launched with the correct CAN params.
