### ISSUE TITLE
CANNOT catch some spesific can message IDs

### ISSUE THREAD

**Issue by mfapakhan** [astuff/kvaser_interface#73]
Hello to everyone;

I am using this repo to run my kvaser device.
After cloning, and build process, I run can_bridge node to read data from my can bus.
In this process, I cannot catch some messages.
Especially to control whether my observation is true, I made some tests and saw that some messages which one of them is especially important for me cannot be caught.

About that, what can be a reason for this situation? What is your comment?

Thanks and best regards.

**Comment by icolwell-as** [comment]
Hi @mfapakhan, the kvaser_interface is basically just a ROS wrapper for KVaser Canlib. 
KVaser canlib comes with a `canmonitor` tool that will print out anything it receives. I suggest trying this tool to see if your messages are able to be seen by the tool.

With canlib installed you can find the tool here:
`/usr/doc/canlib/examples/canmonitor`

**Comment by mfapakhan** [comment]
Hi @icolwell-as, thanks you for your quick response.

I tried your advice. At this directory: /usr/doc/canlib/examples, I found the canmonitor executable file and run it.
While running, I saw the messages at terminal screen:
```
(1) ERROR FRAMECAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
CAN Error Event
 flags:0x20 time:5
(2) ERROR FRAME flags:0x20 time:5
(3) ERROR FRAME flags:0x20 time:5
(4) ERROR FRAME flags:0x20 time:5
(5) ERROR FRAME flags:0x20 time:5
(6) ERROR FRAME flags:0x20 time:6
(7) ERROR FRAME flags:0x20 time:6
(8) ERROR FRAME flags:0x20 time:6
(9) ERROR FRAME flags:0x20 time:6
(10) ERROR FRAME flags:0x20 time:6
(11) ERROR FRAME flags:0x20 time:6
(12) ERROR FRAME flags:0x20 time:6
(13) ERROR FRAME flags:0x20 time:6
(14) ERROR FRAME flags:0x20 time:6
(15) ERROR FRAME flags:0x20 time:6
(16) ERROR FRAME flags:0x20 time:6
(17) ERROR FRAME flags:0x20 time:6
(18) ERROR FRAME flags:0x20 time:6
(19) ERROR FRAME flags:0x20 time:6
```
What can be reason for that?

Also, I want to say that although this errors occur while running the executable, when I use the command: ros2 run kvaser_interface canmonitor or ros2 run kvaser_interface kvaser_can_bridge, I don't get any error. I can read some messages(Not all messages, only some messages) from the bus. Therefore, I did not understand why I get an error while running the canmonitor.

Thanks.

**Comment by mfapakhan** [comment]
Hi @icolwell-as, thanks for your response.
I solved my problem. The problem was due to hardware connections not the kvaser_interface package.
I am closing this issue, you can ignore this issue.

Thanks and best regards.

**Comment by icolwell-as** [comment]
Glad it's working!
