### ISSUE TITLE
result after running the launch

### ISSUE THREAD

**Issue by stdpython** [astuff/kvaser_interface#8]
there is something stuck after running the launch. I am new to ros and kvaser and I just change the can_hardware_id. It seems nothing came out.

PARAMETERS
 * /kvaser_can_bridge/can_bit_rate: 500000
 * /kvaser_can_bridge/can_circuit_id: 0
 * /kvaser_can_bridge/can_hardware_id: 32231
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /
    kvaser_can_bridge (kvaser_interface/kvaser_can_bridge)

auto-starting new master
process[master]: started with pid [21302]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b88297d4-aa9b-11e8-b5eb-80c16e5fb314
process[rosout-1]: started with pid [21316]
started core service [/rosout]
process[kvaser_can_bridge-2]: started with pid [21324]

**Comment by JWhitleyAStuff** [comment]
@stdpython - This output looks correct. It will stay like that as long as the node is running. To look at the data, use `rostopic list` to see the list of published topics and `rostopic echo <topic>` to see the data.

**Comment by JWhitleyAStuff** [comment]
I also recommend the [Schreibotics](https://discord.gg/dze4FTG) Discord server for getting started with ROS (after the official tutorials).
