### ISSUE TITLE
Create jammy dist for kvaser linux

### ISSUE THREAD

**Issue by wep21** [astuff/kvaser_interface#85]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Create jammy dist in https://ppa.launchpadcontent.net/astuff/kvaser-linux/ubuntu/dists/.

**Describe alternatives you've considered**

**Additional context**

**Comment by wep21** [comment]
@icolwell-as Could you create jammy dist for kvaser-linux because Ubuntu 22.04 has been already released?

**Comment by icolwell-as** [comment]
Hi @wep21, the kvaser-linux packages have been released for Jammy. It may take some time until they are available:
https://launchpad.net/~astuff/+archive/ubuntu/kvaser-linux/+packages

Let me know if you run into any issues using them.

**Comment by wep21** [comment]
@icolwell-as Thank you. I confirmed the packages are available for jammy.
