### ISSUE TITLE
Error opening reader: -3 - No available CAN channels were found

### ISSUE THREAD

**Issue by sisaha9** [astuff/kvaser_interface#89]
**Describe the bug**
Exact same issue as #75 but on kernel 5.15.0-46-generic

**To Reproduce**
1. Clone this repository and install dependent libraries as specified in README
2. `ros2 run kvaser_interface list_channels`

**Expected behavior**
A list of channels as expected

**Actual Behavior**
`No channels found.`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 ROS2 Galactic
- Installed from Apt

**Additional context**
Confirmed that the Kvaser device itself is working by using CANKing on Windows

**Comment by icolwell-as** [comment]
Hi @sisaha9, if you run `/usr/doc/canlib/examples/listChannels` do you get the same response?

Can you try uninstalling and then re-installing the `kvaser-drivers-dkms` via apt?
Recently I've seen the kvaser dkms driver fail after what I suspect is a kernel update, it seems like the DKMS portion fails to rebuild itself properly after the kernel changes.

**Comment by sisaha9** [comment]
Reinstalling worked. Thanks!
